site_name: RL Book Ecosystem
site_description: Documentation for RL book ecosystem
nav:
  - Home: index.md

theme:
  name: material

# Add any other needed settings here (but avoid site_dir/docs_dir entries)
